import { readFile, writeFile } from 'node:fs/promises';

const USERNAME = 'tomasztarlowski';
const README_PATH = 'README.md';
const COPY_PATH = 'data/project-copy.json';
const START = '<!-- profile:public-work:start -->';
const END = '<!-- profile:public-work:end -->';

const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;

async function github(path) {
  const headers = {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': `${USERNAME}-profile-updater`
  };

  if (token) headers.Authorization = `Bearer ${token}`;

  const response = await fetch(`https://api.github.com${path}`, { headers });
  if (!response.ok) {
    const body = await response.text();
    throw new Error(`GitHub API ${response.status} for ${path}: ${body}`);
  }

  return response.json();
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function formatDate(value) {
  return new Intl.DateTimeFormat('pl-PL', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    timeZone: 'Europe/Warsaw'
  }).format(new Date(value));
}

function chunk(items, size) {
  const rows = [];
  for (let index = 0; index < items.length; index += size) {
    rows.push(items.slice(index, index + size));
  }
  return rows;
}

function repoMeta(repo, override) {
  return [
    override.type,
    repo.language,
    repo.stargazers_count ? `${repo.stargazers_count} ${repo.stargazers_count === 1 ? 'gwiazdka' : 'gwiazdki'}` : null,
    `aktualizacja ${formatDate(repo.pushed_at || repo.updated_at)}`
  ].filter(Boolean);
}

function renderRepoCard(repo, override = {}) {
  const description = override.description || repo.description || 'Public project from my product/dev lab.';
  const meta = repoMeta(repo, override).map(escapeHtml).join(' · ');
  const topics = (repo.topics || []).slice(0, 4);

  const topicLine = topics.length
    ? `<br /><sub>${topics.map((topic) => `#${escapeHtml(topic)}`).join(' ')}</sub>`
    : '';

  return [
    '<td width="50%" valign="top">',
    `  <a href="${repo.html_url}"><strong>${escapeHtml(repo.name)}</strong></a>`,
    `  <br />${escapeHtml(description)}`,
    `  <br /><sub>${meta}</sub>${topicLine}`,
    '</td>'
  ].join('\n');
}

function renderTable(repos, copy) {
  const rows = chunk(repos, 2).map((pair) => {
    const cells = pair.map((repo) => renderRepoCard(repo, copy.projects?.[repo.name]));
    if (cells.length === 1) cells.push('<td width="50%" valign="top"></td>');
    return `<tr>\n${cells.join('\n')}\n</tr>`;
  });

  return `<table>\n${rows.join('\n')}\n</table>`;
}

function languageSummary(repos) {
  const counts = repos.reduce((acc, repo) => {
    if (!repo.language) return acc;
    acc.set(repo.language, (acc.get(repo.language) || 0) + 1);
    return acc;
  }, new Map());

  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 4)
    .map(([language]) => language)
    .join(' · ');
}

function renderSection(repos, copy) {
  const publicOwnRepos = repos.filter((repo) => !repo.fork && repo.name !== USERNAME);
  const byName = new Map(publicOwnRepos.map((repo) => [repo.name, repo]));
  const orderedFeatured = (copy.featuredOrder || [])
    .map((name) => byName.get(name))
    .filter(Boolean);

  const rest = publicOwnRepos
    .filter((repo) => !orderedFeatured.some((featured) => featured.name === repo.name))
    .sort((a, b) => new Date(b.pushed_at || b.updated_at) - new Date(a.pushed_at || a.updated_at));

  const featured = [...orderedFeatured, ...rest].slice(0, 6);
  const refreshedAt = new Intl.DateTimeFormat('pl-PL', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    timeZone: 'Europe/Warsaw'
  }).format(new Date());
  const languages = languageSummary(publicOwnRepos) || 'web · product · automation';

  return [
    START,
    '<!-- Generated by scripts/update-profile.mjs -->',
    '',
    `<p><strong>${publicOwnRepos.length}</strong> oryginalnych publicznych repozytoriów · <strong>${languages}</strong> · odświeżone ${refreshedAt}</p>`,
    '',
    renderTable(featured, copy),
    '',
    `<sub>Źródło: <a href="https://github.com/${USERNAME}?tab=repositories">repozytoria GitHub</a>. Forki są tu celowo ukryte, żeby profil prowadził do oryginalnej pracy.</sub>`,
    END
  ].join('\n');
}

const [readme, copyRaw, repos] = await Promise.all([
  readFile(README_PATH, 'utf8'),
  readFile(COPY_PATH, 'utf8'),
  github(`/users/${USERNAME}/repos?per_page=100&type=owner&sort=pushed`)
]);

const copy = JSON.parse(copyRaw);
const startIndex = readme.indexOf(START);
const endIndex = readme.indexOf(END);

if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
  throw new Error(`Could not find ${START} / ${END} markers in ${README_PATH}`);
}

const before = readme.slice(0, startIndex);
const after = readme.slice(endIndex + END.length);
const nextReadme = `${before}${renderSection(repos, copy)}${after}`;

await writeFile(README_PATH, nextReadme);
